#:schema node_modules/wrangler/config-schema.json
name = "gt-cal"
main = "src/index.js"
compatibility_date = "2024-04-23"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "CALENDAR_CACHE"
bucket_name = "gtcal"